### ISSUE TITLE
Not running in Windows 11

### ISSUE THREAD

**Issue by shawngiese** [Rectus/openxr-steamvr-passthrough#10]
When I run passthrough-setup.exe in Windows 11 22H2, I receive the error "This app can't run on your PC". An ideas?

**Comment by Rectus** [comment]
Try running it as administrator. 

If that doesn't work, check if there is a more detailed log entry of why it isn't running. It should be available in
the Windows Event Viewer under Windows Logs ->Applications.

**Comment by shawngiese** [comment]
Ah, it was my antivirus that was flagging it and blocking the .exe and .dll.

**Comment by Rectus** [comment]
Ah, good to know. The setup program is probably flagged because it modifies the Windows registry.

**Comment by shawngiese** [comment]
It was just being flagged becuase it was relatively unknown among my antivirus sw users.
