### ISSUE TITLE
WMR

### ISSUE THREAD

**Issue by 88888888owo88888888** [Rectus/openxr-steamvr-passthrough#11]
are you planning to make a version for WMR reverb g2 ?

**Comment by Rectus** [comment]
I'm not planning on it. Unfortunately, I don't own the hardware, and even if it did, it doesn't have any officially supported way of accessing the camera images. 

Apparently there is a fork of mbuccias WMR passthrough layer with G2 support though:
https://github.com/Ultrasic/WMR-Passthrough/tree/feature/reverb-g2-support
