### ISSUE TITLE
Install-Layer not installing?

### ISSUE THREAD

**Issue by robotdestroy** [Rectus/openxr-steamvr-passthrough#2]
Sorry for the troubleshooting issue, but when I Run with PowerShell on the Install-Layer file the API layer does not seem to install. I confirmed this by going to my %APPDATA% folder, I do not see the OpenXR SteamVR Passthrough folder. Are there instructions to manually install or any alternative ideas as to how to install? Thanks!

**Comment by robotdestroy** [comment]
Also just to confirm I did installed Visual Studio C++ Redistributable (64 bit) first.

**Comment by Rectus** [comment]
The install script will add a registry key with the current location of the dll file to  `\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1\ApiLayers\Implicit\`. You can use regedit to verify that it has been added. If you have run the script from multiple locations, there may be multiple copies of the key that can interfere with each other.

**Comment by robotdestroy** [comment]
Thank you. When I look for that registry it is missing. There is no Implicit folder. I was running the script from my \Downloads folder. Should that be aok?

**Comment by Rectus** [comment]
It should work, as long as you don't move the files afterwards. The script should ask for admin privileges to write the registry key, so be sure to allow it.

**Comment by robotdestroy** [comment]
Ah, it did not ask for admin privileges, let me investigate why.

**Comment by robotdestroy** [comment]
I see, I had to Set-ExecutionPolicy RemoteSigned in PowerShell in order for it to run the script. Thanks for your help!

**Comment by Rectus** [comment]
I replaced the scripts with an easier to use utility. 

https://github.com/Rectus/openxr-steamvr-passthrough/releases/tag/version_0.1.1
