### ISSUE TITLE
Adding (actual) depth to the passthrough

### ISSUE THREAD

**Issue by nailuj05** [Rectus/openxr-steamvr-passthrough#3]
Hey, 
First of all I am really impressed with this passthrough layer. I think the Index has a lot of MR possibilites that are completely unused right now. In you readme you state that the depth is not currently accessible to devs. 
I recently tried out these depth camera demos that were "discovered" (their code was in the openvr repo for a long time) and I was wondering whether the code for this demos can be transferred over to this passthrough layer.
The code in question:
https://github.com/ValveSoftware/openvr/tree/master/samples/hmd_opencv_sandbox
The compiled binaries:
https://drive.google.com/file/d/1JTFfcJezEqeqS2xuZr5e1bjFJl_0iThY/view

Video of the passthrough demo:
https://twitter.com/SadlyItsBradley/status/1596546359121031168

Best regards

**Comment by Rectus** [comment]
It would be possible, although it might be a lot of work implementing it, and porting the OpenGL code to the DirectX renderers. The demo uses OpenCV for the reconstruction, and from what I understand, it is relatively slow compared to software designed for real-time passthrough, so I'm unsure how usable it is in practice.

**Comment by nailuj05** [comment]
In your todo you mention you want to add OpenGL support, would that make things easier?

**Comment by Rectus** [comment]
I don't know. Even with support for OpenGL, it would still need to get the output of the decomposition to the DirectX renderers, or it wouldn't support DirectX applications.

**Comment by nailuj05** [comment]
Okay, thank you for the input!

**Comment by Rectus** [comment]
I added support for this in 0.2.0. It still needs a bunch of work though.
https://github.com/Rectus/openxr-steamvr-passthrough/releases/tag/v0.2.0-beta

**Comment by nailuj05** [comment]
Exciting, I will definitely check it out!

**Comment by Rectus** [comment]
Closing this as it has been implemented for a long time.
