### ISSUE TITLE
Failed to access windows registry! With admin.

### ISSUE THREAD

**Issue by Roll675** [Rectus/openxr-steamvr-passthrough#4]
Running the API installer as admin says "Failed to access windows registry!"
I have tried making sure its on my windows boot drive, tried on another drive as well. 
It seems there is some issue accessing the registry that I cannot figure out.

**Comment by Rectus** [comment]
It might be failing in case all the registry keys aren't there, I'll have to check. In the mean time, you can download the 0.1.0 release and use the install script from that.

**Comment by Rectus** [comment]
I updated it, see if that fixes it:
https://github.com/Rectus/openxr-steamvr-passthrough/releases/tag/v0.1.2-beta

**Comment by Roll675** [comment]
> I updated it, see if that fixes it: https://github.com/Rectus/openxr-steamvr-passthrough/releases/tag/v0.1.2-beta

This fixed my issue! Thank you so much!
