### ISSUE TITLE
Setup application does not start in Windows 11

### ISSUE THREAD

**Issue by Defalting** [Rectus/openxr-steamvr-passthrough#5]
Just to let you know, I tried running the installer on windows 11. It crashes on boot, and the only solution was to run it in windows 8 compatibility mode inside the program settings.

I assume certain API calls in windows 11 native are triggering a crash. Would submit a crash report, but IDK where the crash log is in this.

**Comment by Rectus** [comment]
Thanks. The installer shouldn't put out any logs by itself, so the only place it would possibly be logged is the Windows Event Viewer under Windows Logs ->Applications.

**Comment by Defalting** [comment]
![image](https://user-images.githubusercontent.com/28060353/205504302-4270dcdf-84a9-401d-82f4-0fc894eecb58.png)
![image](https://user-images.githubusercontent.com/28060353/205504319-a161aaa7-f79f-418c-84a0-98d4e34ddf10.png)
Here, four of these happen (as in, 4 events in total), two the same as each other. I'd send in the saved log itself, but Git is preventing me from sending it

**Comment by Rectus** [comment]
This should be fixed now in version 0.1.3
https://github.com/Rectus/openxr-steamvr-passthrough/releases/tag/v0.1.3-beta

**Comment by Rectus** [comment]
There was an extra `Release()` call on a ComPtr object. Not sure why it didn't crash on Windows 10.
